import type { Metadata } from "next";
import { Martel } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Menu from "@/components/Menu";

const martel = Martel({
  variable: "--font-martel",
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale} style={{ scrollBehavior: 'smooth' }} suppressHydrationWarning>
      <body className={`${martel.variable} antialiased bg-[#F9F7F2] text-[#333333] font-serif`} suppressHydrationWarning>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Menu />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
